// ============================================================
// MOCK DATA — EduMali
// Dernière mise à jour : 2026
// ============================================================

export const mockAnnales = [
  { id: "1",  titre: "BAC 2025 — Mathématiques TSE",       matiere: "Mathématiques",  serie: "TSE",    niveau: "Terminale", annee: 2025, type: "annale",  telechargements: 420,  taille_mb: 1.2, is_premium_only: false },
  { id: "2",  titre: "BAC 2025 — Physique-Chimie TSE",     matiere: "Physique-Chimie", serie: "TSE",   niveau: "Terminale", annee: 2025, type: "annale",  telechargements: 310,  taille_mb: 0.9, is_premium_only: false },
  { id: "3",  titre: "BAC 2025 — SVT TSEXP",               matiere: "SVT",            serie: "TSEXP",  niveau: "Terminale", annee: 2025, type: "annale",  telechargements: 280,  taille_mb: 1.5, is_premium_only: false },
  { id: "4",  titre: "Cours résumé — Analyse L1 USTTB",    matiere: "Mathématiques",  serie: "L1",     niveau: "Licence",   annee: 2025, type: "resume",  telechargements: 195,  taille_mb: 2.1, is_premium_only: false },
  { id: "5",  titre: "BAC 2024 — Mathématiques TSE",       matiere: "Mathématiques",  serie: "TSE",    niveau: "Terminale", annee: 2024, type: "annale",  telechargements: 1850, taille_mb: 1.1, is_premium_only: false },
  { id: "6",  titre: "BAC 2024 — Philosophie TLL",         matiere: "Philosophie",    serie: "TLL",    niveau: "Terminale", annee: 2024, type: "annale",  telechargements: 1420, taille_mb: 0.8, is_premium_only: false },
  { id: "7",  titre: "Corrigé BAC 2024 — Maths TSE",       matiere: "Mathématiques",  serie: "TSE",    niveau: "Terminale", annee: 2024, type: "corrige", telechargements: 2300, taille_mb: 1.4, is_premium_only: true  },
  { id: "8",  titre: "TP Chimie — USTTB L2",               matiere: "Physique-Chimie", serie: "L2",    niveau: "Licence",   annee: 2024, type: "tp",      telechargements: 530,  taille_mb: 3.2, is_premium_only: false },
  { id: "9",  titre: "BAC 2023 — Anglais TAL",             matiere: "Anglais",        serie: "TAL",    niveau: "Terminale", annee: 2023, type: "annale",  telechargements: 640,  taille_mb: 0.7, is_premium_only: false },
  { id: "10", titre: "BAC 2023 — Français TLL",            matiere: "Français",       serie: "TLL",    niveau: "Terminale", annee: 2023, type: "annale",  telechargements: 1100, taille_mb: 1.0, is_premium_only: false },
  { id: "11", titre: "BAC 2023 — Histoire-Géo TSS",        matiere: "Histoire-Géo",   serie: "TSS",    niveau: "Terminale", annee: 2023, type: "annale",  telechargements: 890,  taille_mb: 1.3, is_premium_only: false },
  { id: "12", titre: "Résumé Droit constitutionnel L2",    matiere: "Droit",          serie: "L2",     niveau: "Licence",   annee: 2023, type: "resume",  telechargements: 760,  taille_mb: 0.6, is_premium_only: false },
  { id: "13", titre: "BAC 2022 — Mathématiques TSE",       matiere: "Mathématiques",  serie: "TSE",    niveau: "Terminale", annee: 2022, type: "annale",  telechargements: 2100, taille_mb: 1.2, is_premium_only: false },
  { id: "14", titre: "Corrigé BAC 2022 — Philo TLL",       matiere: "Philosophie",    serie: "TLL",    niveau: "Terminale", annee: 2022, type: "corrige", telechargements: 1700, taille_mb: 0.9, is_premium_only: true  },
];

export const mockForumPosts = [
  {
    id: "1",
    titre: "Comment réviser efficacement les maths pour le BAC 2026 ?",
    body: "Salut ! Je suis en Terminale TSE et les épreuves approchent. Méthodes de révision pour les maths ?",
    categorie: "Révisions",
    votes: 47,
    answers: 14,
    answers_count: 14,
    is_resolved: false,
    username: "AminataBa",
    created_at: "2026-03-28",
  },
  {
    id: "2",
    titre: "Quelle filière choisir après un BAC TSE à l'USTTB ?",
    body: "J'ai eu mon BAC TSE mention Bien et j'hésite entre médecine, ingénierie informatique et génie civil.",
    categorie: "Orientation",
    votes: 35,
    answers: 18,
    answers_count: 18,
    is_resolved: true,
    username: "OumarDiallo",
    created_at: "2026-03-25",
  },
  {
    id: "3",
    titre: "Annales de physique 2025 disponibles ?",
    body: "Est-ce que quelqu'un a les annales de physique-chimie du BAC 2025 ? Je ne les trouve pas.",
    categorie: "Ressources",
    votes: 12,
    answers: 5,
    answers_count: 5,
    is_resolved: false,
    username: "FatouKane",
    created_at: "2026-03-20",
  },
  {
    id: "4",
    titre: "Conseils pour l'oral de français BAC 2026",
    body: "L'oral approche et je suis un peu stressé. Des anciens peuvent partager des conseils ?",
    categorie: "Révisions",
    votes: 58,
    answers: 21,
    answers_count: 21,
    is_resolved: false,
    username: "IbrahimSissoko",
    created_at: "2026-03-18",
  },
  {
    id: "5",
    titre: "Guide complet — Bourses d'études au Mali 2026",
    body: "Je partage toutes les infos sur les bourses disponibles pour les étudiants maliens : AEEM, État, étrangères...",
    categorie: "Bourses",
    votes: 89,
    answers: 32,
    answers_count: 32,
    is_resolved: false,
    username: "MariamaTraoré",
    created_at: "2026-03-15",
  },
  {
    id: "6",
    titre: "Programmation Python — par où commencer ?",
    body: "Je veux apprendre Python pour la fac d'informatique. Quelles ressources recommandez-vous ?",
    categorie: "Informatique",
    votes: 29,
    answers: 11,
    answers_count: 11,
    is_resolved: true,
    username: "ModiboCoulibaly",
    created_at: "2026-03-10",
  },
];

export const mockEtablissements = [
  { id: "1", nom: "Université des Sciences, des Techniques et des Technologies de Bamako (USTTB)", ville: "Bamako", description: "Premier établissement scientifique du Mali, offrant des formations en sciences, médecine et ingénierie.", filieres: 12 },
  { id: "2", nom: "Université des Lettres et des Sciences Humaines de Bamako (ULSHB)", ville: "Bamako", description: "Spécialisée en lettres, sciences humaines, langues et communication.", filieres: 8 },
  { id: "3", nom: "Institut Polytechnique Rural (IPR/IFRA) de Katibougou", ville: "Koulikoro", description: "Formation en agronomie, élevage et sciences rurales.", filieres: 6 },
  { id: "4", nom: "École Nationale d'Ingénieurs (ENI-ABT)", ville: "Bamako", description: "Formation d'ingénieurs dans divers domaines techniques.", filieres: 10 },
  { id: "5", nom: "Université de Ségou", ville: "Ségou", description: "Université régionale avec formations diversifiées.", filieres: 7 },
];

export const mockCalendrier = [
  { id: "1", titre: "Rentrée scolaire 2025-2026",            date_debut: "2025-10-01", type: "rentrée"     },
  { id: "2", titre: "Examens du 1er semestre 2025-2026",     date_debut: "2026-01-15", type: "examen"      },
  { id: "3", titre: "Vacances de février 2026",              date_debut: "2026-02-14", type: "vacances"    },
  { id: "4", titre: "Examens du 2e semestre 2025-2026",      date_debut: "2026-05-18", type: "examen"      },
  { id: "5", titre: "BAC 2026 — Épreuves écrites",           date_debut: "2026-06-10", type: "examen"      },
  { id: "6", titre: "Résultats du BAC 2026",                 date_debut: "2026-07-15", type: "résultats"   },
  { id: "7", titre: "Inscriptions universitaires 2026-2027", date_debut: "2026-09-01", type: "inscription" },
  { id: "8", titre: "Rentrée universitaire 2026-2027",       date_debut: "2026-10-15", type: "rentrée"     },
];

export const mockFormations = [
  {
    id: "f1",
    titre: "Maîtrisez les Maths du BAC TSE en 30 jours",
    description: "Méthodes, exercices corrigés et annales commentées. Idéal pour la Terminale TSE.",
    formateur: { username: "MathProBamako", full_name: "Dr. Amadou Kouyaté", avatar_url: null },
    prix_fcfa: 8000,
    niveau: "Terminale",
    categorie: "Mathématiques",
    image_url: null,
    nb_inscrits: 284,
    nb_modules: 12,
    duree_heures: 18,
    note_moyenne: 4.7,
    is_published: true,
    created_at: "2026-01-10",
  },
  {
    id: "f2",
    titre: "Introduction au Droit Malien — L1 ULSHB",
    description: "Cours complet de droit constitutionnel et droit civil adaptés au programme malien.",
    formateur: { username: "MeBarry", full_name: "Me Fatoumata Barry", avatar_url: null },
    prix_fcfa: 6000,
    niveau: "Licence",
    categorie: "Droit",
    image_url: null,
    nb_inscrits: 157,
    nb_modules: 8,
    duree_heures: 14,
    note_moyenne: 4.5,
    is_published: true,
    created_at: "2026-01-20",
  },
  {
    id: "f3",
    titre: "Python pour débutants — Formation complète",
    description: "Apprenez Python de zéro avec des projets pratiques adaptés au contexte africain.",
    formateur: { username: "TechBamako", full_name: "Ibrahim Coulibaly", avatar_url: null },
    prix_fcfa: 12000,
    niveau: "Tous niveaux",
    categorie: "Informatique",
    image_url: null,
    nb_inscrits: 412,
    nb_modules: 20,
    duree_heures: 30,
    note_moyenne: 4.9,
    is_published: true,
    created_at: "2026-02-01",
  },
  {
    id: "f4",
    titre: "Préparation TOEFL & Anglais universitaire",
    description: "Méthodes éprouvées pour réussir le TOEFL et améliorer votre anglais académique.",
    formateur: { username: "EnglishMali", full_name: "Mariam Touré", avatar_url: null },
    prix_fcfa: 10000,
    niveau: "Tous niveaux",
    categorie: "Langues",
    image_url: null,
    nb_inscrits: 93,
    nb_modules: 15,
    duree_heures: 22,
    note_moyenne: 4.6,
    is_published: true,
    created_at: "2026-02-15",
  },
  {
    id: "f5",
    titre: "Comptabilité générale — BTS et Licence Pro",
    description: "Maîtrisez le plan comptable malien, les écritures et les états financiers.",
    formateur: { username: "ComptaPro", full_name: "Seydou Diarra", avatar_url: null },
    prix_fcfa: 7500,
    niveau: "BTS / Licence Pro",
    categorie: "Comptabilité",
    image_url: null,
    nb_inscrits: 198,
    nb_modules: 10,
    duree_heures: 16,
    note_moyenne: 4.4,
    is_published: true,
    created_at: "2026-03-01",
  },
  {
    id: "f6",
    titre: "Chimie organique — USTTB L2 Science",
    description: "Tout le programme de chimie organique L2 avec exercices d'application.",
    formateur: { username: "ChimieUSSTTB", full_name: "Dr. Keïta Boubacar", avatar_url: null },
    prix_fcfa: 5000,
    niveau: "Licence",
    categorie: "Sciences",
    image_url: null,
    nb_inscrits: 67,
    nb_modules: 9,
    duree_heures: 12,
    note_moyenne: 4.3,
    is_published: true,
    created_at: "2026-03-10",
  },
];

export const matieres = [
  "Mathématiques", "Physique-Chimie", "SVT", "Philosophie",
  "Français", "Anglais", "Histoire-Géo", "Droit", "Informatique",
];
export const series = ["TSE", "TSEXP", "TLL", "TAL", "TSS", "L1", "L2", "L3", "Master"];
export const niveaux = ["Lycée", "Terminale", "BTS", "Licence", "Master", "Doctorat", "Professionnel"];
export const typesRessource = ["annale", "cours", "corrige", "resume", "tp"];
export const annees = [2025, 2024, 2023, 2022, 2021, 2020];
export const villes = ["Bamako", "Koulikoro", "Ségou", "Sikasso", "Mopti", "Tombouctou", "Gao", "Kayes"];
export const categoriesFormation = [
  "Mathématiques", "Sciences", "Droit", "Informatique",
  "Langues", "Comptabilité", "Gestion", "Médecine",
];
export const categoriesForum = [
  "Révisions", "Orientation", "Ressources", "Bourses",
  "Informatique", "Forum libre",
];
